# Generated by Django 4.2.7 on 2023-11-29 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_carritodecompras_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritodecompras',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente'),
        ),
    ]
