# Generated by Django 4.2.7 on 2023-11-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_boleta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carritodecompras',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='subtotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
